opt_out_usage

require "json"
require "fileutils"
require "tmpdir"
require "digest"
require "openssl"

def wildcard_provisioning_profile_path
  File.expand_path("../generator/Wildcard.mobileprovision", __dir__)
end

def signing_identity_from_profile(path)
  profile = FastlaneCore::ProvisioningProfile.parse(path)
  certificate = OpenSSL::X509::Certificate.new(profile.fetch("DeveloperCertificates").first.string)
  certificate.subject.to_a.find { |name, _value, _type| name == "CN" }&.[](1) ||
    UI.user_error!("Could not determine the signing identity from #{path}")
end

def ipa_info_from_path(ipa_path)
  info_plist = FastlaneCore::IpaFileAnalyser.fetch_info_plist_file(ipa_path)

  {
    "version" => info_plist["CFBundleShortVersionString"],
    "build" => info_plist["CFBundleVersion"],
    "bundle_id" => info_plist["CFBundleIdentifier"],
    "app_name" => info_plist["CFBundleName"]
  }
end

def file_md5(path)
  Digest::MD5.file(path).hexdigest
end

def release_md5s(release)
  body = release&.dig("body").to_s
  ipa_match_groups = /Original \.ipa MD5 ([a-f0-9]{32})/.match(body)
  provision_match_groups = /Provision MD5 ([a-f0-9]{32})/.match(body)

  {
    "ipa" => ipa_match_groups&.[](1),
    "provision" => provision_match_groups&.[](1)
  }
end

def upload_required?(app, release)
  return true if release.nil?

  md5s = release_md5s(release)
  return true if md5s["ipa"].nil? || md5s["provision"].nil?

  md5s["ipa"] != app["original_ipa_md5"] || md5s["provision"] != app["provision_md5"]
end

desc "Create or refresh wildcard signing assets with match"
lane :gen_provision do
  api_key = app_store_connect_api_key(
    key_id: ENV["APP_STORE_CONNECT_KEY_ID"],
    issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
    key_content: ENV["APP_STORE_CONNECT_KEY_CONTENT_BASE64"],
    is_key_content_base64: true
  )

  match(
    type: "adhoc",
    app_identifier: "*",
    profile_name: "match AdHoc wildcard",
    git_url: ENV["MATCH_GIT_URL"],
    api_key: api_key,
    readonly: false,
    force: true,
    include_mac_in_profiles: true
  )

  match_profile_path = ENV["sigh_*_adhoc_profile-path"]
  UI.user_error!("Match did not provide the wildcard Ad Hoc profile path") if match_profile_path.to_s.empty?

  FileUtils.mkdir_p(File.dirname(wildcard_provisioning_profile_path))
  FileUtils.cp(match_profile_path, wildcard_provisioning_profile_path)
end

desc "Get ipa version, build, bundle id and name"
lane :get_ipa_info do |options|
  ipa_info_from_path(options[:ipa_path])
end

desc "Scan all the ipas in `ipas` folder"
lane :iterate_over_ipas do
  apps = []
  Dir.glob("#{File.expand_path("..", Dir.pwd)}/ipas/*").each do |path|
    next unless File.directory?(path) # skip the loop if the file is not a directory

    app_tag = File.basename(path) # got app tag
    ipa = Dir.glob("#{path}/*.ipa")[0] # scaning for ipa file

    ipa_info = ipa_info_from_path(ipa) # get ipa file info
    ipa_info["tag"] = app_tag
    ipa_info["path"] = ipa

    datafile = Dir.glob("#{path}/data.json")
    unless datafile.empty?
      file = File.open datafile[0]
      data = JSON.load file

      ipa_info = ipa_info.merge(data)

      file.close
    end

    apps.append(ipa_info)
  end
  # return array
  apps
end

desc "Creates plist files for ad hoc download"
lane :create_plists do |options|
  apps = options[:apps]
  if apps.nil?
    apps = iterate_over_ipas
  end

  template_file = File.open "../plist_template.txt"
  template = template_file.read
  template_file.close
  apps.each do |app|
    plist_data = template.dup

    # Replacing template variables
    plist_data.sub! "{ipa_url}", "#{ENV['GIT_URI']}/#{ENV['REPO']}/releases/download/#{app["tag"]}/app.ipa"
    plist_data.sub! "{bundle_identifier}", app["bundle_id"]
    plist_data.sub! "{title}", app["app_name"]

    plist_path = "../apps/#{app["tag"]}"

    # Create dirs if they're empty
    FileUtils.mkdir_p plist_path
    # Writing
    File.write("#{plist_path}/Info.plist", plist_data)
  end
end

desc "Resign ipas with mobileprovision"
lane :resign_ipas do |options|
  apps = options[:apps]
  if apps.nil?
    apps = iterate_over_ipas
  end

  apps.each do |app|
    app["original_ipa_md5"] = file_md5(app["path"])
    app["provision_md5"] = file_md5(wildcard_provisioning_profile_path)

    existing_release = get_github_release(url: ENV["REPO"], version: app["tag"], api_token: ENV["GITHUB_TOKEN"])
    unless upload_required?(app, existing_release)
      UI.success "App [#{app['tag']}] '#{app['app_name']}' already exists with same ipa/provision md5, skipping resign"
      next
    end

    existing_md5s = release_md5s(existing_release)
    if !existing_release.nil? && existing_md5s["provision"] != app["provision_md5"]
      UI.important "Provisioning profile has changed, reuploading App [#{app['tag']}] '#{app['app_name']}' ..."
    end

    Dir.mktmpdir do |dir|
      # Copy ipa to temp dir
      FileUtils.cp(app["path"], dir)
      copied_file = "#{dir}/#{File.basename(app['path'])}"

      # Renaming to app.ipa
      temp_path = "#{dir}/app.ipa"
      File.rename(copied_file, temp_path)
      
      resign(
        ipa: temp_path,
        signing_identity: signing_identity_from_profile(wildcard_provisioning_profile_path),
        provisioning_profile: wildcard_provisioning_profile_path,
        # use_app_entitlements: true
      )

      app["temp_path"] = temp_path

      puts "Provision MD5 #{app['provision_md5']}"
      puts "Original .ipa MD5 #{app['original_ipa_md5']}"
      
      upload_ipa(app: app, existing_release: existing_release)
    end

  end
end

desc "Upload ipa to github release section"
lane :upload_ipa do |options|
  app = options[:app]
  existing_release = options[:existing_release]
  if existing_release.nil?
    existing_release = get_github_release(url: ENV["REPO"], version: app["tag"], api_token: ENV["GITHUB_TOKEN"])
  end

  unless existing_release.nil?
    # Delete existing release on GH
    response = github_api(
      server_url: "https://api.github.com",
      api_token: ENV["GITHUB_TOKEN"],
      http_method: "DELETE",
      path: "/repos/#{ENV['REPO']}/git/refs/tags/#{app['tag']}"
    )
    # Give GH some time to handle this
    sleep 3
  end

  github_release = set_github_release(
    repository_name: ENV["REPO"],
    api_token: ENV["GITHUB_TOKEN"],
    tag_name: app["tag"],
    name: app["app_name"],
    description: "#{app['app_name']} #{app['version']} (#{app['build']})\n#{app['bundle_id']}\nOriginal .ipa MD5 #{app['original_ipa_md5']}\nProvision MD5 #{app['provision_md5']}",
    commitish: "master",
    upload_assets: [app["temp_path"]]
  )
end

desc "Generate readme based on ipas available"
lane :create_readme do |options|
  apps = options[:apps]
  if apps.nil?
    apps = iterate_over_ipas
  end
  readme = "# Signed IPAs\n\n"

  apps.each do |app|
    app_text = "### #{app['app_name']}"

    # Additional title from data.json
    unless app["title"].nil?
      app_text += " | " + app["title"]
    end

    app_text += "\n\n"
    # Version and build
    app_text += "> v#{app['version']} (#{app['build']})"
    # Download via plist
    app_text += "\n\n"
    app_text += "<a href=\"itms-services://?action=download-manifest&amp;url=https://raw.githubusercontent.com/#{ENV['REPO']}/master/apps/#{app['tag']}/Info.plist\">📥 Download</a>"
    
    app_text += "\n\n"

    # Additioanl comment from data.json
    unless app["comment"].nil?
      app_text += "<details><summary>Description</summary>\n"
      app_text += app["comment"]
      app_text += "\n</details>"
      app_text += "\n\n"
    end


    readme += app_text
  end

  readme += "__Please, refer to [/readme-dev.md](/readme-dev.md) for instructions__"

  File.write("../readme.md", readme)
end

desc "Run full update of mobileprovision, ipas and readme"
lane :full_update do
  gen_provision()
  update()
end

desc "Commit updated dirs"
lane :commit_update do
  sh "cd .. && git add apps/* readme.md && git commit -m 'Update apps' && git push origin master"
end

desc "Run update of ipas and readme"
lane :update do
  apps = iterate_over_ipas
  puts apps
  resign_ipas(apps: apps)
  create_plists(apps: apps)
  create_readme(apps: apps)
  begin
    commit_update()
  rescue => ex
    UI.error("Error commiting update. Probably nothing to commit 🤔")
  end 
end
